# Generated by Django 2.1.8 on 2019-05-17 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0006_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='img',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
